# Preprocessing Resume Dataset Folder  (Pertimbangan)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
id = '1d2WUxxfgbZ9K_yjxc5PNBZhlKsCaFSEL'
url = f'https://drive.google.com/uc?id={id}'
df = pd.read_csv(url)
df.head()

             Category                                             Resume
0  Frontend Developer  As a seasoned Frontend Developer, I have a pro...
1   Backend Developer  With a solid background in Backend Development...
2    Python Developer  As a Python Developer, I leverage my expertise...
3      Data Scientist  With a background in Data Science, I possess a...
4  Frontend Developer  Experienced Frontend Developer with a passion ...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  400 non-null    object
 1   Resume    400 non-null    object
dtypes: object(2)
memory usage: 6.4+ KB

In [4]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 188 entries, 0 to 399
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  188 non-null    object
 1   Resume    188 non-null    object
dtypes: object(2)
memory usage: 4.4+ KB

In [5]:
# Role Normalization

def map_role(title):
    title = title.lower()
    
    if 'data analyst' in title:
        return 'data analyst'
    elif 'frontend' in title or 'front end' in title or 'react' in title or 'front-end' in title:
        return 'frontend'
    elif "backend" in title or 'back end' in title or "node" in title or 'back-end' in title:
        return "backend"
    else:
        return None
df['role'] = df['Category'].apply(map_role)
df = df[df['role'].notnull()].copy()
df

,Category,Resume,role
0,Frontend Developer,"As a seasoned Frontend Developer, I have a pro...",frontend
1,Backend Developer,With a solid background in Backend Development...,backend
4,Frontend Developer,Experienced Frontend Developer with a passion ...,frontend
5,Frontend Developer,Passionate Frontend Developer with over 4 year...,frontend
6,Backend Developer,Seasoned Backend Developer with a proven track...,backend
7,Backend Developer,Dynamic Backend Developer with a passion for b...,backend
12,Frontend Developer,Detail-oriented Frontend Developer with a stro...,frontend
13,Backend Developer,Experienced Backend Developer with a focus on ...,backend
17,Frontend Developer,Experienced Frontend Developer with a solid ba...,frontend
18,Backend Developer,Seasoned Backend Developer with a focus on arc...,backend
22,Frontend Developer,Enthusiastic Frontend Developer with a strong ...,frontend
23,Backend Developer,Experienced Backend Developer with a focus on ...,backend
74,Frontend Developer,Passionate Frontend Developer with a creative ...,frontend
75,Frontend Developer,Innovative Frontend Developer with a focus on ...,frontend
76,Frontend Developer,Creative Frontend Developer with a passion for...,frontend
77,Frontend Developer,Dynamic Frontend Developer with a strong backg...,frontend
78,Frontend Developer,Experienced Frontend Developer specializing in...,frontend
79,Frontend Developer,Passionate Frontend Developer with a strong fo...,frontend
80,Frontend Developer,Creative Frontend Developer with a passion for...,frontend
81,Frontend Developer,Innovative Frontend Developer with a focus on ...,frontend
82,Frontend Developer,Dynamic Frontend Developer with a passion for ...,frontend
83,Frontend Developer,Experienced Frontend Developer specializing in...,frontend
94,Backend Developer,Results-driven Backend Developer with expertis...,backend
95,Backend Developer,Passionate Backend Developer with a focus on b...,backend
96,Backend Developer,Innovative Backend Developer with a strong fou...,backend
97,Backend Developer,Dynamic Backend Developer with a passion for b...,backend
98,Backend Developer,Experienced Backend Developer specializing in ...,backend
211,Frontend Developer,Experienced Frontend Developer with a passion ...,frontend
212,Frontend Developer,Passionate Frontend Developer with expertise i...,frontend
213,Frontend Developer,Innovative Frontend Developer with a creative ...,frontend
214,Frontend Developer,Dynamic Frontend Developer with a focus on del...,frontend
223,Backend Developer,Experienced Backend Developer with a strong ba...,backend
224,Backend Developer,Passionate Backend Developer with expertise in...,backend
225,Backend Developer,Innovative Backend Developer with a creative a...,backend
226,Backend Developer,Dynamic Backend Developer with a focus on deli...,backend
283,Backend Developer,Experienced Backend Developer with a strong ba...,backend
284,Backend Developer,Passionate Backend Developer with expertise in...,backend
285,Backend Developer,Innovative Backend Developer with a creative a...,backend
286,Backend Developer,Dynamic Backend Developer with a focus on desi...,backend
303,Frontend Developer,Experienced Frontend Developer with a passion ...,frontend
304,Frontend Developer,Creative Frontend Developer with a focus on cr...,frontend
305,Frontend Developer,Innovative Frontend Developer with a strong de...,frontend
306,Frontend Developer,Dynamic Frontend Developer with a passion for ...,frontend

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, 0 to 306
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  43 non-null     object
 1   Resume    43 non-null     object
 2   role      43 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

In [7]:
import re

def casefolding(text):
    return text.lower()

def cleaning(text):
    text = re.sub(r"http\S+", "", text)
    
    text = text.replace('\n', ' ')
    text = text.replace('*','')
    
    text = text.strip()
    
    text = re.sub(r'\s+', ' ', text)
    
    return text

for col in df.columns:
    df.loc[:, f"clean_{col}"] = df[col].apply(casefolding)
    df.loc[:, f"clean_{col}"] = df[f"clean_{col}"].apply(cleaning)
df

,Category,Resume,role,clean_Category,clean_Resume,clean_role
0,Frontend Developer,"As a seasoned Frontend Developer, I have a pro...",frontend,frontend developer,"as a seasoned frontend developer, i have a pro...",frontend
1,Backend Developer,With a solid background in Backend Development...,backend,backend developer,with a solid background in backend development...,backend
4,Frontend Developer,Experienced Frontend Developer with a passion ...,frontend,frontend developer,experienced frontend developer with a passion ...,frontend
5,Frontend Developer,Passionate Frontend Developer with over 4 year...,frontend,frontend developer,passionate frontend developer with over 4 year...,frontend
6,Backend Developer,Seasoned Backend Developer with a proven track...,backend,backend developer,seasoned backend developer with a proven track...,backend
7,Backend Developer,Dynamic Backend Developer with a passion for b...,backend,backend developer,dynamic backend developer with a passion for b...,backend
12,Frontend Developer,Detail-oriented Frontend Developer with a stro...,frontend,frontend developer,detail-oriented frontend developer with a stro...,frontend
13,Backend Developer,Experienced Backend Developer with a focus on ...,backend,backend developer,experienced backend developer with a focus on ...,backend
17,Frontend Developer,Experienced Frontend Developer with a solid ba...,frontend,frontend developer,experienced frontend developer with a solid ba...,frontend
18,Backend Developer,Seasoned Backend Developer with a focus on arc...,backend,backend developer,seasoned backend developer with a focus on arc...,backend
22,Frontend Developer,Enthusiastic Frontend Developer with a strong ...,frontend,frontend developer,enthusiastic frontend developer with a strong ...,frontend
23,Backend Developer,Experienced Backend Developer with a focus on ...,backend,backend developer,experienced backend developer with a focus on ...,backend
74,Frontend Developer,Passionate Frontend Developer with a creative ...,frontend,frontend developer,passionate frontend developer with a creative ...,frontend
75,Frontend Developer,Innovative Frontend Developer with a focus on ...,frontend,frontend developer,innovative frontend developer with a focus on ...,frontend
76,Frontend Developer,Creative Frontend Developer with a passion for...,frontend,frontend developer,creative frontend developer with a passion for...,frontend
77,Frontend Developer,Dynamic Frontend Developer with a strong backg...,frontend,frontend developer,dynamic frontend developer with a strong backg...,frontend
78,Frontend Developer,Experienced Frontend Developer specializing in...,frontend,frontend developer,experienced frontend developer specializing in...,frontend
79,Frontend Developer,Passionate Frontend Developer with a strong fo...,frontend,frontend developer,passionate frontend developer with a strong fo...,frontend
80,Frontend Developer,Creative Frontend Developer with a passion for...,frontend,frontend developer,creative frontend developer with a passion for...,frontend
81,Frontend Developer,Innovative Frontend Developer with a focus on ...,frontend,frontend developer,innovative frontend developer with a focus on ...,frontend
82,Frontend Developer,Dynamic Frontend Developer with a passion for ...,frontend,frontend developer,dynamic frontend developer with a passion for ...,frontend
83,Frontend Developer,Experienced Frontend Developer specializing in...,frontend,frontend developer,experienced frontend developer specializing in...,frontend
94,Backend Developer,Results-driven Backend Developer with expertis...,backend,backend developer,results-driven backend developer with expertis...,backend
95,Backend Developer,Passionate Backend Developer with a focus on b...,backend,backend developer,passionate backend developer with a focus on b...,backend
96,Backend Developer,Innovative Backend Developer with a strong fou...,backend,backend developer,innovative backend developer with a strong fou...,backend
97,Backend Developer,Dynamic Backend Developer with a passion for b...,backend,backend developer,dynamic backend developer with a passion for b...,backend
98,Backend Developer,Experienced Backend Developer specializing in ...,backend,backend developer,experienced backend developer specializing in ...,backend
211,Frontend Developer,Experienced Frontend Developer with a passion ...,frontend,frontend developer,experienced frontend developer with a passion ...,frontend
212,Frontend Developer,Passionate Frontend Developer with expertise i...,frontend,frontend developer,passionate frontend developer with expertise i...,frontend
213,Frontend Developer,Innovative Frontend Developer with a creative ...,frontend,frontend developer,innovative frontend developer with a creative ...,frontend
214,Frontend Developer,Dynamic Frontend Developer with a focus on del...,frontend,frontend developer,dynamic frontend developer with a focus on del...,frontend
223,Backend Developer,Experienced Backend Developer with a strong ba...,backend,backend developer,experienced backend developer with a strong ba...,backend
224,Backend Developer,Passionate Backend Developer with expertise in...,backend,backend developer,passionate backend developer with expertise in...,backend
225,Backend Developer,Innovative Backend Developer with a creative a...,backend,backend developer,innovative backend developer with a creative a...,backend
226,Backend Developer,Dynamic Backend Developer with a focus on deli...,backend,backend developer,dynamic backend developer with a focus on deli...,backend
283,Backend Developer,Experienced Backend Developer with a strong ba...,backend,backend developer,experienced backend developer with a strong ba...,backend
284,Backend Developer,Passionate Backend Developer with expertise in...,backend,backend developer,passionate backend developer with expertise in...,backend
285,Backend Developer,Innovative Backend Developer with a creative a...,backend,backend developer,innovative backend developer with a creative a...,backend
286,Backend Developer,Dynamic Backend Developer with a focus on desi...,backend,backend developer,dynamic backend developer with a focus on desi...,backend
303,Frontend Developer,Experienced Frontend Developer with a passion ...,frontend,frontend developer,experienced frontend developer with a passion ...,frontend
304,Frontend Developer,Creative Frontend Developer with a focus on cr...,frontend,frontend developer,creative frontend developer with a focus on cr...,frontend
305,Frontend Developer,Innovative Frontend Developer with a strong de...,frontend,frontend developer,innovative frontend developer with a strong de...,frontend
306,Frontend Developer,Dynamic Frontend Developer with a passion for ...,frontend,frontend developer,dynamic frontend developer with a passion for ...,frontend

In [8]:
df['role'].value_counts()

role
frontend    24
backend     19
Name: count, dtype: int64