# Preprocessing Job Descriptions 2025 – Tech & Non-Tech Roles Folder

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
id = '13iAabpkvzN9XgfUhD0m4ZIaIr2UUDPIh'
url = f'https://drive.google.com/uc?id={id}'
df = pd.read_csv(url)
df.head()

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords
0,NET-F-001,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Framework; .NET Core f...,Assist in coding and debugging applications; L...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
1,NET-F-002,.NET Developer,Fresher,0-1,C#; .NET Framework basics; ASP.NET; Razor; HTM...,Write simple C# programs under guidance; Suppo...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
2,NET-F-003,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Core; ASP.NET MVC; HTM...,Contribute to development of small modules; As...,.NET; C#; ASP.NET MVC; SQL Server; Entity Fram...
3,NET-F-004,.NET Developer,Fresher,0-1,C#; .NET Framework; ASP.NET basics; SQL Server...,Support in software design documentation; Assi...,.NET; C#; SQL Server; Entity Framework; ASP.NET
4,NET-F-005,.NET Developer,Fresher,0-1,C#; ASP.NET; MVC; Entity Framework basics; SQL...,Learn to design and build ASP.NET applications...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068 entries, 0 to 1067
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   JobID              1068 non-null   object
 1   Title              1067 non-null   object
 2   ExperienceLevel    1068 non-null   object
 3   YearsOfExperience  1068 non-null   object
 4   Skills             1068 non-null   object
 5   Responsibilities   1068 non-null   object
 6   Keywords           1068 non-null   object
dtypes: object(7)
memory usage: 58.5+ KB

In [4]:
df.columns

Index(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills',
       'Responsibilities', 'Keywords'],
      dtype='object')

In [5]:
df.drop(columns=['JobID', 'YearsOfExperience', 'Keywords'], inplace=True)
df.head()

,Title,ExperienceLevel,Skills,Responsibilities
0,.NET Developer,Fresher,C#; VB.NET basics; .NET Framework; .NET Core f...,Assist in coding and debugging applications; L...
1,.NET Developer,Fresher,C#; .NET Framework basics; ASP.NET; Razor; HTM...,Write simple C# programs under guidance; Suppo...
2,.NET Developer,Fresher,C#; VB.NET basics; .NET Core; ASP.NET MVC; HTM...,Contribute to development of small modules; As...
3,.NET Developer,Fresher,C#; .NET Framework; ASP.NET basics; SQL Server...,Support in software design documentation; Assi...
4,.NET Developer,Fresher,C#; ASP.NET; MVC; Entity Framework basics; SQL...,Learn to design and build ASP.NET applications...

In [6]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1050 entries, 0 to 1067
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             1050 non-null   object
 1   ExperienceLevel   1050 non-null   object
 2   Skills            1050 non-null   object
 3   Responsibilities  1050 non-null   object
dtypes: object(4)
memory usage: 41.0+ KB

In [7]:
# Role Normalization

def map_role(title):
    title = title.lower()
    
    if 'data analyst' in title:
        return 'data analyst'
    elif 'frontend' in title or 'front end' in title or 'react' in title or 'front-end' in title:
        return 'frontend'
    elif "backend" in title or 'back end' in title or "node" in title or 'back-end' in title:
        return "backend"
    else:
        return None
df['role'] = df['Title'].apply(map_role)
df = df[df['role'].notnull()].copy()
df

,Title,ExperienceLevel,Skills,Responsibilities,role
100,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Flask; Djan...,Assist in building server-side applications; D...,backend
101,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Flask; Djan...,Implement scalable backend services; Develop A...,backend
102,Backend Developer - Entry Level,Fresher,Node.js; Python; Express.js; Flask; Django; My...,Develop and maintain backend APIs; Optimize da...,backend
103,Backend Developer - Entry Level,Fresher,Node.js; Python; Express.js; Flask; Django; My...,Server-side development for web and mobile app...,backend
104,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Flask; Djan...,Design and develop backend services; Write eff...,backend
105,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Flask; Djan...,Develop backend modules; Assist in API develop...,backend
106,Backend Developer - Entry Level,Fresher,Node.js; Python; Express.js; Django; Flask; My...,Assist in developing backend services for web ...,backend
107,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Django; Fla...,Server-side components for web and mobile apps...,backend
108,Backend Developer - Entry Level,Fresher,Node.js; Python; Express.js; Flask; Django; My...,Assist in backend development of scalable APIs...,backend
109,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Django; Fla...,Assist in backend development; Develop APIs; M...,backend
110,Backend Developer - Experienced,Experienced,Node.js; Python; Java; Go; Express.js; Django;...,"Design, develop, and maintain backend services...",backend
111,Backend Developer - Experienced,Experienced,Java; Go; Node.js; Spring Boot; Express.js; Po...,Lead backend development for fintech applicati...,backend
112,Backend Developer - Experienced,Experienced,Python; Node.js; Django; Flask; Express.js; Po...,Architect backend systems for healthcare appli...,backend
113,Backend Developer - Experienced,Experienced,Node.js; Python; Java; Express.js; Django; Fla...,Lead backend engineering for e-commerce platfo...,backend
114,Backend Developer - Experienced,Experienced,Python; Node.js; Go; Django; Flask; Express.js...,Design backend services for AI-powered applica...,backend
115,Backend Developer - Experienced,Experienced,Node.js; Java; Python; Express.js; Spring Boot...,Lead backend infrastructure for logistics plat...,backend
116,Backend Developer - Experienced,Experienced,Python; Node.js; Java; Django; Flask; Express....,Architect backend solutions for SaaS applicati...,backend
117,Backend Developer - Experienced,Experienced,Java; Go; Python; Spring Boot; Express.js; Dja...,Develop backend systems for fintech and bankin...,backend
118,Backend Developer - Experienced,Experienced,Node.js; Python; Java; Express.js; Django; Spr...,Lead backend development for large-scale socia...,backend
119,Backend Developer - Experienced,Experienced,Node.js; Python; Go; Express.js; Django; Flask...,Architect backend solutions for media streamin...,backend
300,Data Analyst - Fresher,Entry-Level,SQL; Python; R; SAS; Tableau; Power BI; Matplo...,Assist in analyzing datasets; Create dashboard...,data analyst
301,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Excel chart...,Perform data extraction and cleaning; Create v...,data analyst
302,Data Analyst - Fresher,Entry-Level,SQL; Python; R; SAS; Tableau; Power BI; Matplo...,Assist with data cleaning and exploratory data...,data analyst
303,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Excel; Pand...,Support data extraction and cleaning; Generate...,data analyst
304,Data Analyst - Fresher,Entry-Level,SQL; Python; R; SAS; Tableau; Power BI; Matplo...,Assist in cleaning datasets; Build simple dash...,data analyst
305,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Matplotlib;...,Support teams in analyzing datasets; Perform d...,data analyst
306,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Excel chart...,Assist in ETL processes; Perform data cleaning...,data analyst
307,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Excel chart...,Perform data cleaning; Generate dashboards; As...,data analyst
308,Data Analyst - Fresher,Entry-Level,SQL; Python; R; SAS; Tableau; Power BI; Matplo...,Assist teams with SQL queries; Process data us...,data analyst
309,Data Analyst - Experienced,Senior-Level,Predictive modeling; Machine learning algorith...,Lead analytics projects; Develop predictive mo...,data analyst
310,Data Analyst - Experienced,Senior-Level,Predictive modeling; Machine learning; Time-se...,Design and implement advanced analytics soluti...,data analyst
311,Data Analyst - Experienced,Senior-Level,Predictive modeling; Advanced analytics; Machi...,Lead business intelligence projects; Develop p...,data analyst
312,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Develop advanced dashboards; Optimize SQL quer...,data analyst
313,Data Analyst - Experienced,Senior-Level,Predictive modeling; Machine learning; Advance...,Lead analytics and BI projects; Manage data pi...,data analyst
314,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Design and implement analytics dashboards; Opt...,data analyst
315,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Lead analytics initiatives; Design predictive ...,data analyst
316,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; SAS; Predictive model...,Manage large-scale analytics projects; Impleme...,data analyst
317,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Design and implement analytics dashboards; Opt...,data analyst
318,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Lead analytics and BI projects; Manage data pi...,data analyst
319,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Manage large-scale analytics projects; Impleme...,data analyst
342,Data Analyst / Data Scientist Intern,Fresher,Python; R; SQL; Pandas; NumPy; Matplotlib; Sea...,"Assist in data collection, cleaning, and analy...",data analyst
427,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Build responsive and interactive web pages; Im...,frontend
428,Frontend Developer - Entry Level,Entry-Level,HTML5; CSS3; JavaScript (ES6+); React; Vue.js;...,Develop web interfaces for internal tools; Imp...,frontend
429,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Work on small projects and personal applicatio...,frontend
430,Frontend Developer - Entry Level,Entry-Level,HTML5; CSS3; JavaScript (ES6+); React basics; ...,Assist in designing and coding responsive web ...,frontend
431,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Create and maintain frontend components; Parti...,frontend
432,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Develop interactive UI pages for internal dash...,frontend
433,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Vue.js ba...,Assist in implementing UI features for web app...,frontend
434,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Build responsive web pages; Assist in integrat...,frontend
435,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Vue.js ba...,Assist in creating web interfaces and componen...,frontend
436,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Work on academic and personal projects; Develo...,frontend
437,Frontend Developer - Experienced,Mid-Senior Level,HTML5; CSS3; JavaScript (ES6+); React/Redux; A...,Design and develop advanced frontend applicati...,frontend
438,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Lead frontend development for scalable applica...,frontend
439,Frontend Developer - Experienced,Senior-Level,Advanced React; Angular; Vue.js; HTML; CSS; Ja...,Architect and implement frontend solutions; Le...,frontend
440,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Lead frontend initiatives for e-commerce platf...,frontend
441,Frontend Developer - Experienced,Senior-Level,"Advanced React (Hooks, Redux); Angular; Vue.js...",Architect scalable web dashboards and SPAs; Op...,frontend
442,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Lead frontend development for SaaS products; I...,frontend
443,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Build and optimize frontend for media streamin...,frontend
444,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Lead frontend for AI-powered dashboards; Build...,frontend

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59 entries, 100 to 444
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             59 non-null     object
 1   ExperienceLevel   59 non-null     object
 2   Skills            59 non-null     object
 3   Responsibilities  59 non-null     object
 4   role              59 non-null     object
dtypes: object(5)
memory usage: 2.8+ KB

In [9]:
import re

def casefolding(text):
    return text.lower()

def cleaning(text):
    text = re.sub(r"http\S+", "", text)
    
    text = text.replace('\n', ' ')
    text = text.replace('*','')
    text = text.replace(';',',')
    
    text = text.strip()
    
    text = re.sub(r'\s+', ' ', text)
    
    return text

for col in df.columns:
    df.loc[:, f"clean_{col}"] = df[col].apply(casefolding)
    df.loc[:, f"clean_{col}"] = df[f"clean_{col}"].apply(cleaning)
df

,Title,ExperienceLevel,Skills,Responsibilities,role,clean_Title,clean_ExperienceLevel,clean_Skills,clean_Responsibilities,clean_role
100,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Flask; Djan...,Assist in building server-side applications; D...,backend,backend developer - entry level,fresher,"node.js, python, java, express.js, flask, djan...","assist in building server-side applications, d...",backend
101,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Flask; Djan...,Implement scalable backend services; Develop A...,backend,backend developer - entry level,fresher,"node.js, python, java, express.js, flask, djan...","implement scalable backend services, develop a...",backend
102,Backend Developer - Entry Level,Fresher,Node.js; Python; Express.js; Flask; Django; My...,Develop and maintain backend APIs; Optimize da...,backend,backend developer - entry level,fresher,"node.js, python, express.js, flask, django, my...","develop and maintain backend apis, optimize da...",backend
103,Backend Developer - Entry Level,Fresher,Node.js; Python; Express.js; Flask; Django; My...,Server-side development for web and mobile app...,backend,backend developer - entry level,fresher,"node.js, python, express.js, flask, django, my...",server-side development for web and mobile app...,backend
104,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Flask; Djan...,Design and develop backend services; Write eff...,backend,backend developer - entry level,fresher,"node.js, python, java, express.js, flask, djan...","design and develop backend services, write eff...",backend
105,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Flask; Djan...,Develop backend modules; Assist in API develop...,backend,backend developer - entry level,fresher,"node.js, python, java, express.js, flask, djan...","develop backend modules, assist in api develop...",backend
106,Backend Developer - Entry Level,Fresher,Node.js; Python; Express.js; Django; Flask; My...,Assist in developing backend services for web ...,backend,backend developer - entry level,fresher,"node.js, python, express.js, django, flask, my...",assist in developing backend services for web ...,backend
107,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Django; Fla...,Server-side components for web and mobile apps...,backend,backend developer - entry level,fresher,"node.js, python, java, express.js, django, fla...",server-side components for web and mobile apps...,backend
108,Backend Developer - Entry Level,Fresher,Node.js; Python; Express.js; Flask; Django; My...,Assist in backend development of scalable APIs...,backend,backend developer - entry level,fresher,"node.js, python, express.js, flask, django, my...",assist in backend development of scalable apis...,backend
109,Backend Developer - Entry Level,Fresher,Node.js; Python; Java; Express.js; Django; Fla...,Assist in backend development; Develop APIs; M...,backend,backend developer - entry level,fresher,"node.js, python, java, express.js, django, fla...","assist in backend development, develop apis, m...",backend
110,Backend Developer - Experienced,Experienced,Node.js; Python; Java; Go; Express.js; Django;...,"Design, develop, and maintain backend services...",backend,backend developer - experienced,experienced,"node.js, python, java, go, express.js, django,...","design, develop, and maintain backend services...",backend
111,Backend Developer - Experienced,Experienced,Java; Go; Node.js; Spring Boot; Express.js; Po...,Lead backend development for fintech applicati...,backend,backend developer - experienced,experienced,"java, go, node.js, spring boot, express.js, po...",lead backend development for fintech applicati...,backend
112,Backend Developer - Experienced,Experienced,Python; Node.js; Django; Flask; Express.js; Po...,Architect backend systems for healthcare appli...,backend,backend developer - experienced,experienced,"python, node.js, django, flask, express.js, po...",architect backend systems for healthcare appli...,backend
113,Backend Developer - Experienced,Experienced,Node.js; Python; Java; Express.js; Django; Fla...,Lead backend engineering for e-commerce platfo...,backend,backend developer - experienced,experienced,"node.js, python, java, express.js, django, fla...",lead backend engineering for e-commerce platfo...,backend
114,Backend Developer - Experienced,Experienced,Python; Node.js; Go; Django; Flask; Express.js...,Design backend services for AI-powered applica...,backend,backend developer - experienced,experienced,"python, node.js, go, django, flask, express.js...",design backend services for ai-powered applica...,backend
115,Backend Developer - Experienced,Experienced,Node.js; Java; Python; Express.js; Spring Boot...,Lead backend infrastructure for logistics plat...,backend,backend developer - experienced,experienced,"node.js, java, python, express.js, spring boot...",lead backend infrastructure for logistics plat...,backend
116,Backend Developer - Experienced,Experienced,Python; Node.js; Java; Django; Flask; Express....,Architect backend solutions for SaaS applicati...,backend,backend developer - experienced,experienced,"python, node.js, java, django, flask, express....",architect backend solutions for saas applicati...,backend
117,Backend Developer - Experienced,Experienced,Java; Go; Python; Spring Boot; Express.js; Dja...,Develop backend systems for fintech and bankin...,backend,backend developer - experienced,experienced,"java, go, python, spring boot, express.js, dja...",develop backend systems for fintech and bankin...,backend
118,Backend Developer - Experienced,Experienced,Node.js; Python; Java; Express.js; Django; Spr...,Lead backend development for large-scale socia...,backend,backend developer - experienced,experienced,"node.js, python, java, express.js, django, spr...",lead backend development for large-scale socia...,backend
119,Backend Developer - Experienced,Experienced,Node.js; Python; Go; Express.js; Django; Flask...,Architect backend solutions for media streamin...,backend,backend developer - experienced,experienced,"node.js, python, go, express.js, django, flask...",architect backend solutions for media streamin...,backend
300,Data Analyst - Fresher,Entry-Level,SQL; Python; R; SAS; Tableau; Power BI; Matplo...,Assist in analyzing datasets; Create dashboard...,data analyst,data analyst - fresher,entry-level,"sql, python, r, sas, tableau, power bi, matplo...","assist in analyzing datasets, create dashboard...",data analyst
301,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Excel chart...,Perform data extraction and cleaning; Create v...,data analyst,data analyst - fresher,entry-level,"sql, python, r, tableau, power bi, excel chart...","perform data extraction and cleaning, create v...",data analyst
302,Data Analyst - Fresher,Entry-Level,SQL; Python; R; SAS; Tableau; Power BI; Matplo...,Assist with data cleaning and exploratory data...,data analyst,data analyst - fresher,entry-level,"sql, python, r, sas, tableau, power bi, matplo...",assist with data cleaning and exploratory data...,data analyst
303,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Excel; Pand...,Support data extraction and cleaning; Generate...,data analyst,data analyst - fresher,entry-level,"sql, python, r, tableau, power bi, excel, pand...","support data extraction and cleaning, generate...",data analyst
304,Data Analyst - Fresher,Entry-Level,SQL; Python; R; SAS; Tableau; Power BI; Matplo...,Assist in cleaning datasets; Build simple dash...,data analyst,data analyst - fresher,entry-level,"sql, python, r, sas, tableau, power bi, matplo...","assist in cleaning datasets, build simple dash...",data analyst
305,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Matplotlib;...,Support teams in analyzing datasets; Perform d...,data analyst,data analyst - fresher,entry-level,"sql, python, r, tableau, power bi, matplotlib,...","support teams in analyzing datasets, perform d...",data analyst
306,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Excel chart...,Assist in ETL processes; Perform data cleaning...,data analyst,data analyst - fresher,entry-level,"sql, python, r, tableau, power bi, excel chart...","assist in etl processes, perform data cleaning...",data analyst
307,Data Analyst - Fresher,Entry-Level,SQL; Python; R; Tableau; Power BI; Excel chart...,Perform data cleaning; Generate dashboards; As...,data analyst,data analyst - fresher,entry-level,"sql, python, r, tableau, power bi, excel chart...","perform data cleaning, generate dashboards, as...",data analyst
308,Data Analyst - Fresher,Entry-Level,SQL; Python; R; SAS; Tableau; Power BI; Matplo...,Assist teams with SQL queries; Process data us...,data analyst,data analyst - fresher,entry-level,"sql, python, r, sas, tableau, power bi, matplo...","assist teams with sql queries, process data us...",data analyst
309,Data Analyst - Experienced,Senior-Level,Predictive modeling; Machine learning algorith...,Lead analytics projects; Develop predictive mo...,data analyst,data analyst - experienced,senior-level,"predictive modeling, machine learning algorith...","lead analytics projects, develop predictive mo...",data analyst
310,Data Analyst - Experienced,Senior-Level,Predictive modeling; Machine learning; Time-se...,Design and implement advanced analytics soluti...,data analyst,data analyst - experienced,senior-level,"predictive modeling, machine learning, time-se...",design and implement advanced analytics soluti...,data analyst
311,Data Analyst - Experienced,Senior-Level,Predictive modeling; Advanced analytics; Machi...,Lead business intelligence projects; Develop p...,data analyst,data analyst - experienced,senior-level,"predictive modeling, advanced analytics, machi...","lead business intelligence projects, develop p...",data analyst
312,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Develop advanced dashboards; Optimize SQL quer...,data analyst,data analyst - experienced,senior-level,"advanced sql, python, r, predictive modeling, ...","develop advanced dashboards, optimize sql quer...",data analyst
313,Data Analyst - Experienced,Senior-Level,Predictive modeling; Machine learning; Advance...,Lead analytics and BI projects; Manage data pi...,data analyst,data analyst - experienced,senior-level,"predictive modeling, machine learning, advance...","lead analytics and bi projects, manage data pi...",data analyst
314,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Design and implement analytics dashboards; Opt...,data analyst,data analyst - experienced,senior-level,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt...",data analyst
315,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Lead analytics initiatives; Design predictive ...,data analyst,data analyst - experienced,senior-level,"advanced sql, python, r, predictive modeling, ...","lead analytics initiatives, design predictive ...",data analyst
316,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; SAS; Predictive model...,Manage large-scale analytics projects; Impleme...,data analyst,data analyst - experienced,senior-level,"advanced sql, python, r, sas, predictive model...","manage large-scale analytics projects, impleme...",data analyst
317,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Design and implement analytics dashboards; Opt...,data analyst,data analyst - experienced,senior-level,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt...",data analyst
318,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Lead analytics and BI projects; Manage data pi...,data analyst,data analyst - experienced,senior-level,"advanced sql, python, r, predictive modeling, ...","lead analytics and bi projects, manage data pi...",data analyst
319,Data Analyst - Experienced,Senior-Level,Advanced SQL; Python; R; Predictive modeling; ...,Manage large-scale analytics projects; Impleme...,data analyst,data analyst - experienced,senior-level,"advanced sql, python, r, predictive modeling, ...","manage large-scale analytics projects, impleme...",data analyst
342,Data Analyst / Data Scientist Intern,Fresher,Python; R; SQL; Pandas; NumPy; Matplotlib; Sea...,"Assist in data collection, cleaning, and analy...",data analyst,data analyst / data scientist intern,fresher,"python, r, sql, pandas, numpy, matplotlib, sea...","assist in data collection, cleaning, and analy...",data analyst
427,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Build responsive and interactive web pages; Im...,frontend,frontend developer - entry level,entry-level,"html, css, javascript, react basics, angular b...","build responsive and interactive web pages, im...",frontend
428,Frontend Developer - Entry Level,Entry-Level,HTML5; CSS3; JavaScript (ES6+); React; Vue.js;...,Develop web interfaces for internal tools; Imp...,frontend,frontend developer - entry level,entry-level,"html5, css3, javascript (es6+), react, vue.js,...","develop web interfaces for internal tools, imp...",frontend
429,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Work on small projects and personal applicatio...,frontend,frontend developer - entry level,entry-level,"html, css, javascript, react basics, angular b...",work on small projects and personal applicatio...,frontend
430,Frontend Developer - Entry Level,Entry-Level,HTML5; CSS3; JavaScript (ES6+); React basics; ...,Assist in designing and coding responsive web ...,frontend,frontend developer - entry level,entry-level,"html5, css3, javascript (es6+), react basics, ...",assist in designing and coding responsive web ...,frontend
431,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Create and maintain frontend components; Parti...,frontend,frontend developer - entry level,entry-level,"html, css, javascript, react basics, angular b...","create and maintain frontend components, parti...",frontend
432,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Develop interactive UI pages for internal dash...,frontend,frontend developer - entry level,entry-level,"html, css, javascript, react basics, angular b...",develop interactive ui pages for internal dash...,frontend
433,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Vue.js ba...,Assist in implementing UI features for web app...,frontend,frontend developer - entry level,entry-level,"html, css, javascript, react basics, vue.js ba...",assist in implementing ui features for web app...,frontend
434,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Build responsive web pages; Assist in integrat...,frontend,frontend developer - entry level,entry-level,"html, css, javascript, react basics, angular b...","build responsive web pages, assist in integrat...",frontend
435,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Vue.js ba...,Assist in creating web interfaces and componen...,frontend,frontend developer - entry level,entry-level,"html, css, javascript, react basics, vue.js ba...",assist in creating web interfaces and componen...,frontend
436,Frontend Developer - Entry Level,Entry-Level,HTML; CSS; JavaScript; React basics; Angular b...,Work on academic and personal projects; Develo...,frontend,frontend developer - entry level,entry-level,"html, css, javascript, react basics, angular b...","work on academic and personal projects, develo...",frontend
437,Frontend Developer - Experienced,Mid-Senior Level,HTML5; CSS3; JavaScript (ES6+); React/Redux; A...,Design and develop advanced frontend applicati...,frontend,frontend developer - experienced,mid-senior level,"html5, css3, javascript (es6+), react/redux, a...",design and develop advanced frontend applicati...,frontend
438,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Lead frontend development for scalable applica...,frontend,frontend developer - experienced,senior-level,"react/redux, angular, vue.js, html, css, javas...",lead frontend development for scalable applica...,frontend
439,Frontend Developer - Experienced,Senior-Level,Advanced React; Angular; Vue.js; HTML; CSS; Ja...,Architect and implement frontend solutions; Le...,frontend,frontend developer - experienced,senior-level,"advanced react, angular, vue.js, html, css, ja...","architect and implement frontend solutions, le...",frontend
440,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Lead frontend initiatives for e-commerce platf...,frontend,frontend developer - experienced,senior-level,"react/redux, angular, vue.js, html, css, javas...",lead frontend initiatives for e-commerce platf...,frontend
441,Frontend Developer - Experienced,Senior-Level,"Advanced React (Hooks, Redux); Angular; Vue.js...",Architect scalable web dashboards and SPAs; Op...,frontend,frontend developer - experienced,senior-level,"advanced react (hooks, redux), angular, vue.js...","architect scalable web dashboards and spas, op...",frontend
442,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Lead frontend development for SaaS products; I...,frontend,frontend developer - experienced,senior-level,"react/redux, angular, vue.js, html, css, javas...","lead frontend development for saas products, i...",frontend
443,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Build and optimize frontend for media streamin...,frontend,frontend developer - experienced,senior-level,"react/redux, angular, vue.js, html, css, javas...",build and optimize frontend for media streamin...,frontend
444,Frontend Developer - Experienced,Senior-Level,React/Redux; Angular; Vue.js; HTML; CSS; JavaS...,Lead frontend for AI-powered dashboards; Build...,frontend,frontend developer - experienced,senior-level,"react/redux, angular, vue.js, html, css, javas...","lead frontend for ai-powered dashboards, build...",frontend

In [10]:
df['role'].value_counts()

role
data analyst    21
backend         20
frontend        18
Name: count, dtype: int64

In [11]:
df_final = df[['role', 'clean_Skills', 'clean_Responsibilities']].copy()
df_final

,role,clean_Skills,clean_Responsibilities
100,backend,"node.js, python, java, express.js, flask, djan...","assist in building server-side applications, d..."
101,backend,"node.js, python, java, express.js, flask, djan...","implement scalable backend services, develop a..."
102,backend,"node.js, python, express.js, flask, django, my...","develop and maintain backend apis, optimize da..."
103,backend,"node.js, python, express.js, flask, django, my...",server-side development for web and mobile app...
104,backend,"node.js, python, java, express.js, flask, djan...","design and develop backend services, write eff..."
105,backend,"node.js, python, java, express.js, flask, djan...","develop backend modules, assist in api develop..."
106,backend,"node.js, python, express.js, django, flask, my...",assist in developing backend services for web ...
107,backend,"node.js, python, java, express.js, django, fla...",server-side components for web and mobile apps...
108,backend,"node.js, python, express.js, flask, django, my...",assist in backend development of scalable apis...
109,backend,"node.js, python, java, express.js, django, fla...","assist in backend development, develop apis, m..."
110,backend,"node.js, python, java, go, express.js, django,...","design, develop, and maintain backend services..."
111,backend,"java, go, node.js, spring boot, express.js, po...",lead backend development for fintech applicati...
112,backend,"python, node.js, django, flask, express.js, po...",architect backend systems for healthcare appli...
113,backend,"node.js, python, java, express.js, django, fla...",lead backend engineering for e-commerce platfo...
114,backend,"python, node.js, go, django, flask, express.js...",design backend services for ai-powered applica...
115,backend,"node.js, java, python, express.js, spring boot...",lead backend infrastructure for logistics plat...
116,backend,"python, node.js, java, django, flask, express....",architect backend solutions for saas applicati...
117,backend,"java, go, python, spring boot, express.js, dja...",develop backend systems for fintech and bankin...
118,backend,"node.js, python, java, express.js, django, spr...",lead backend development for large-scale socia...
119,backend,"node.js, python, go, express.js, django, flask...",architect backend solutions for media streamin...
300,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist in analyzing datasets, create dashboard..."
301,data analyst,"sql, python, r, tableau, power bi, excel chart...","perform data extraction and cleaning, create v..."
302,data analyst,"sql, python, r, sas, tableau, power bi, matplo...",assist with data cleaning and exploratory data...
303,data analyst,"sql, python, r, tableau, power bi, excel, pand...","support data extraction and cleaning, generate..."
304,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist in cleaning datasets, build simple dash..."
305,data analyst,"sql, python, r, tableau, power bi, matplotlib,...","support teams in analyzing datasets, perform d..."
306,data analyst,"sql, python, r, tableau, power bi, excel chart...","assist in etl processes, perform data cleaning..."
307,data analyst,"sql, python, r, tableau, power bi, excel chart...","perform data cleaning, generate dashboards, as..."
308,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist teams with sql queries, process data us..."
309,data analyst,"predictive modeling, machine learning algorith...","lead analytics projects, develop predictive mo..."
310,data analyst,"predictive modeling, machine learning, time-se...",design and implement advanced analytics soluti...
311,data analyst,"predictive modeling, advanced analytics, machi...","lead business intelligence projects, develop p..."
312,data analyst,"advanced sql, python, r, predictive modeling, ...","develop advanced dashboards, optimize sql quer..."
313,data analyst,"predictive modeling, machine learning, advance...","lead analytics and bi projects, manage data pi..."
314,data analyst,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt..."
315,data analyst,"advanced sql, python, r, predictive modeling, ...","lead analytics initiatives, design predictive ..."
316,data analyst,"advanced sql, python, r, sas, predictive model...","manage large-scale analytics projects, impleme..."
317,data analyst,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt..."
318,data analyst,"advanced sql, python, r, predictive modeling, ...","lead analytics and bi projects, manage data pi..."
319,data analyst,"advanced sql, python, r, predictive modeling, ...","manage large-scale analytics projects, impleme..."
342,data analyst,"python, r, sql, pandas, numpy, matplotlib, sea...","assist in data collection, cleaning, and analy..."
427,frontend,"html, css, javascript, react basics, angular b...","build responsive and interactive web pages, im..."
428,frontend,"html5, css3, javascript (es6+), react, vue.js,...","develop web interfaces for internal tools, imp..."
429,frontend,"html, css, javascript, react basics, angular b...",work on small projects and personal applicatio...
430,frontend,"html5, css3, javascript (es6+), react basics, ...",assist in designing and coding responsive web ...
431,frontend,"html, css, javascript, react basics, angular b...","create and maintain frontend components, parti..."
432,frontend,"html, css, javascript, react basics, angular b...",develop interactive ui pages for internal dash...
433,frontend,"html, css, javascript, react basics, vue.js ba...",assist in implementing ui features for web app...
434,frontend,"html, css, javascript, react basics, angular b...","build responsive web pages, assist in integrat..."
435,frontend,"html, css, javascript, react basics, vue.js ba...",assist in creating web interfaces and componen...
436,frontend,"html, css, javascript, react basics, angular b...","work on academic and personal projects, develo..."
437,frontend,"html5, css3, javascript (es6+), react/redux, a...",design and develop advanced frontend applicati...
438,frontend,"react/redux, angular, vue.js, html, css, javas...",lead frontend development for scalable applica...
439,frontend,"advanced react, angular, vue.js, html, css, ja...","architect and implement frontend solutions, le..."
440,frontend,"react/redux, angular, vue.js, html, css, javas...",lead frontend initiatives for e-commerce platf...
441,frontend,"advanced react (hooks, redux), angular, vue.js...","architect scalable web dashboards and spas, op..."
442,frontend,"react/redux, angular, vue.js, html, css, javas...","lead frontend development for saas products, i..."
443,frontend,"react/redux, angular, vue.js, html, css, javas...",build and optimize frontend for media streamin...
444,frontend,"react/redux, angular, vue.js, html, css, javas...","lead frontend for ai-powered dashboards, build..."

In [12]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59 entries, 100 to 444
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   role                    59 non-null     object
 1   clean_Skills            59 non-null     object
 2   clean_Responsibilities  59 non-null     object
dtypes: object(3)
memory usage: 1.8+ KB

In [13]:
df_final.rename(columns={'clean_Skills': 'skills', 'clean_Responsibilities': 'description'}, inplace=True)
df_final

,role,skills,description
100,backend,"node.js, python, java, express.js, flask, djan...","assist in building server-side applications, d..."
101,backend,"node.js, python, java, express.js, flask, djan...","implement scalable backend services, develop a..."
102,backend,"node.js, python, express.js, flask, django, my...","develop and maintain backend apis, optimize da..."
103,backend,"node.js, python, express.js, flask, django, my...",server-side development for web and mobile app...
104,backend,"node.js, python, java, express.js, flask, djan...","design and develop backend services, write eff..."
105,backend,"node.js, python, java, express.js, flask, djan...","develop backend modules, assist in api develop..."
106,backend,"node.js, python, express.js, django, flask, my...",assist in developing backend services for web ...
107,backend,"node.js, python, java, express.js, django, fla...",server-side components for web and mobile apps...
108,backend,"node.js, python, express.js, flask, django, my...",assist in backend development of scalable apis...
109,backend,"node.js, python, java, express.js, django, fla...","assist in backend development, develop apis, m..."
110,backend,"node.js, python, java, go, express.js, django,...","design, develop, and maintain backend services..."
111,backend,"java, go, node.js, spring boot, express.js, po...",lead backend development for fintech applicati...
112,backend,"python, node.js, django, flask, express.js, po...",architect backend systems for healthcare appli...
113,backend,"node.js, python, java, express.js, django, fla...",lead backend engineering for e-commerce platfo...
114,backend,"python, node.js, go, django, flask, express.js...",design backend services for ai-powered applica...
115,backend,"node.js, java, python, express.js, spring boot...",lead backend infrastructure for logistics plat...
116,backend,"python, node.js, java, django, flask, express....",architect backend solutions for saas applicati...
117,backend,"java, go, python, spring boot, express.js, dja...",develop backend systems for fintech and bankin...
118,backend,"node.js, python, java, express.js, django, spr...",lead backend development for large-scale socia...
119,backend,"node.js, python, go, express.js, django, flask...",architect backend solutions for media streamin...
300,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist in analyzing datasets, create dashboard..."
301,data analyst,"sql, python, r, tableau, power bi, excel chart...","perform data extraction and cleaning, create v..."
302,data analyst,"sql, python, r, sas, tableau, power bi, matplo...",assist with data cleaning and exploratory data...
303,data analyst,"sql, python, r, tableau, power bi, excel, pand...","support data extraction and cleaning, generate..."
304,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist in cleaning datasets, build simple dash..."
305,data analyst,"sql, python, r, tableau, power bi, matplotlib,...","support teams in analyzing datasets, perform d..."
306,data analyst,"sql, python, r, tableau, power bi, excel chart...","assist in etl processes, perform data cleaning..."
307,data analyst,"sql, python, r, tableau, power bi, excel chart...","perform data cleaning, generate dashboards, as..."
308,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist teams with sql queries, process data us..."
309,data analyst,"predictive modeling, machine learning algorith...","lead analytics projects, develop predictive mo..."
310,data analyst,"predictive modeling, machine learning, time-se...",design and implement advanced analytics soluti...
311,data analyst,"predictive modeling, advanced analytics, machi...","lead business intelligence projects, develop p..."
312,data analyst,"advanced sql, python, r, predictive modeling, ...","develop advanced dashboards, optimize sql quer..."
313,data analyst,"predictive modeling, machine learning, advance...","lead analytics and bi projects, manage data pi..."
314,data analyst,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt..."
315,data analyst,"advanced sql, python, r, predictive modeling, ...","lead analytics initiatives, design predictive ..."
316,data analyst,"advanced sql, python, r, sas, predictive model...","manage large-scale analytics projects, impleme..."
317,data analyst,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt..."
318,data analyst,"advanced sql, python, r, predictive modeling, ...","lead analytics and bi projects, manage data pi..."
319,data analyst,"advanced sql, python, r, predictive modeling, ...","manage large-scale analytics projects, impleme..."
342,data analyst,"python, r, sql, pandas, numpy, matplotlib, sea...","assist in data collection, cleaning, and analy..."
427,frontend,"html, css, javascript, react basics, angular b...","build responsive and interactive web pages, im..."
428,frontend,"html5, css3, javascript (es6+), react, vue.js,...","develop web interfaces for internal tools, imp..."
429,frontend,"html, css, javascript, react basics, angular b...",work on small projects and personal applicatio...
430,frontend,"html5, css3, javascript (es6+), react basics, ...",assist in designing and coding responsive web ...
431,frontend,"html, css, javascript, react basics, angular b...","create and maintain frontend components, parti..."
432,frontend,"html, css, javascript, react basics, angular b...",develop interactive ui pages for internal dash...
433,frontend,"html, css, javascript, react basics, vue.js ba...",assist in implementing ui features for web app...
434,frontend,"html, css, javascript, react basics, angular b...","build responsive web pages, assist in integrat..."
435,frontend,"html, css, javascript, react basics, vue.js ba...",assist in creating web interfaces and componen...
436,frontend,"html, css, javascript, react basics, angular b...","work on academic and personal projects, develo..."
437,frontend,"html5, css3, javascript (es6+), react/redux, a...",design and develop advanced frontend applicati...
438,frontend,"react/redux, angular, vue.js, html, css, javas...",lead frontend development for scalable applica...
439,frontend,"advanced react, angular, vue.js, html, css, ja...","architect and implement frontend solutions, le..."
440,frontend,"react/redux, angular, vue.js, html, css, javas...",lead frontend initiatives for e-commerce platf...
441,frontend,"advanced react (hooks, redux), angular, vue.js...","architect scalable web dashboards and spas, op..."
442,frontend,"react/redux, angular, vue.js, html, css, javas...","lead frontend development for saas products, i..."
443,frontend,"react/redux, angular, vue.js, html, css, javas...",build and optimize frontend for media streamin...
444,frontend,"react/redux, angular, vue.js, html, css, javas...","lead frontend for ai-powered dashboards, build..."

In [14]:
def preprocessing_lanjutan(text):
    text = text.replace('/', ' ')
    text = text.replace('&', ' ')
    text = re.sub(r"[()]", " ", text)
    
    return text
    
df_final['skills'] = df_final['skills'].apply(preprocessing_lanjutan).copy()
df_final

,role,skills,description
100,backend,"node.js, python, java, express.js, flask, djan...","assist in building server-side applications, d..."
101,backend,"node.js, python, java, express.js, flask, djan...","implement scalable backend services, develop a..."
102,backend,"node.js, python, express.js, flask, django, my...","develop and maintain backend apis, optimize da..."
103,backend,"node.js, python, express.js, flask, django, my...",server-side development for web and mobile app...
104,backend,"node.js, python, java, express.js, flask, djan...","design and develop backend services, write eff..."
105,backend,"node.js, python, java, express.js, flask, djan...","develop backend modules, assist in api develop..."
106,backend,"node.js, python, express.js, django, flask, my...",assist in developing backend services for web ...
107,backend,"node.js, python, java, express.js, django, fla...",server-side components for web and mobile apps...
108,backend,"node.js, python, express.js, flask, django, my...",assist in backend development of scalable apis...
109,backend,"node.js, python, java, express.js, django, fla...","assist in backend development, develop apis, m..."
110,backend,"node.js, python, java, go, express.js, django,...","design, develop, and maintain backend services..."
111,backend,"java, go, node.js, spring boot, express.js, po...",lead backend development for fintech applicati...
112,backend,"python, node.js, django, flask, express.js, po...",architect backend systems for healthcare appli...
113,backend,"node.js, python, java, express.js, django, fla...",lead backend engineering for e-commerce platfo...
114,backend,"python, node.js, go, django, flask, express.js...",design backend services for ai-powered applica...
115,backend,"node.js, java, python, express.js, spring boot...",lead backend infrastructure for logistics plat...
116,backend,"python, node.js, java, django, flask, express....",architect backend solutions for saas applicati...
117,backend,"java, go, python, spring boot, express.js, dja...",develop backend systems for fintech and bankin...
118,backend,"node.js, python, java, express.js, django, spr...",lead backend development for large-scale socia...
119,backend,"node.js, python, go, express.js, django, flask...",architect backend solutions for media streamin...
300,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist in analyzing datasets, create dashboard..."
301,data analyst,"sql, python, r, tableau, power bi, excel chart...","perform data extraction and cleaning, create v..."
302,data analyst,"sql, python, r, sas, tableau, power bi, matplo...",assist with data cleaning and exploratory data...
303,data analyst,"sql, python, r, tableau, power bi, excel, pand...","support data extraction and cleaning, generate..."
304,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist in cleaning datasets, build simple dash..."
305,data analyst,"sql, python, r, tableau, power bi, matplotlib,...","support teams in analyzing datasets, perform d..."
306,data analyst,"sql, python, r, tableau, power bi, excel chart...","assist in etl processes, perform data cleaning..."
307,data analyst,"sql, python, r, tableau, power bi, excel chart...","perform data cleaning, generate dashboards, as..."
308,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist teams with sql queries, process data us..."
309,data analyst,"predictive modeling, machine learning algorith...","lead analytics projects, develop predictive mo..."
310,data analyst,"predictive modeling, machine learning, time-se...",design and implement advanced analytics soluti...
311,data analyst,"predictive modeling, advanced analytics, machi...","lead business intelligence projects, develop p..."
312,data analyst,"advanced sql, python, r, predictive modeling, ...","develop advanced dashboards, optimize sql quer..."
313,data analyst,"predictive modeling, machine learning, advance...","lead analytics and bi projects, manage data pi..."
314,data analyst,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt..."
315,data analyst,"advanced sql, python, r, predictive modeling, ...","lead analytics initiatives, design predictive ..."
316,data analyst,"advanced sql, python, r, sas, predictive model...","manage large-scale analytics projects, impleme..."
317,data analyst,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt..."
318,data analyst,"advanced sql, python, r, predictive modeling, ...","lead analytics and bi projects, manage data pi..."
319,data analyst,"advanced sql, python, r, predictive modeling, ...","manage large-scale analytics projects, impleme..."
342,data analyst,"python, r, sql, pandas, numpy, matplotlib, sea...","assist in data collection, cleaning, and analy..."
427,frontend,"html, css, javascript, react basics, angular b...","build responsive and interactive web pages, im..."
428,frontend,"html5, css3, javascript es6+ , react, vue.js,...","develop web interfaces for internal tools, imp..."
429,frontend,"html, css, javascript, react basics, angular b...",work on small projects and personal applicatio...
430,frontend,"html5, css3, javascript es6+ , react basics, ...",assist in designing and coding responsive web ...
431,frontend,"html, css, javascript, react basics, angular b...","create and maintain frontend components, parti..."
432,frontend,"html, css, javascript, react basics, angular b...",develop interactive ui pages for internal dash...
433,frontend,"html, css, javascript, react basics, vue.js ba...",assist in implementing ui features for web app...
434,frontend,"html, css, javascript, react basics, angular b...","build responsive web pages, assist in integrat..."
435,frontend,"html, css, javascript, react basics, vue.js ba...",assist in creating web interfaces and componen...
436,frontend,"html, css, javascript, react basics, angular b...","work on academic and personal projects, develo..."
437,frontend,"html5, css3, javascript es6+ , react redux, a...",design and develop advanced frontend applicati...
438,frontend,"react redux, angular, vue.js, html, css, javas...",lead frontend development for scalable applica...
439,frontend,"advanced react, angular, vue.js, html, css, ja...","architect and implement frontend solutions, le..."
440,frontend,"react redux, angular, vue.js, html, css, javas...",lead frontend initiatives for e-commerce platf...
441,frontend,"advanced react hooks, redux , angular, vue.js...","architect scalable web dashboards and spas, op..."
442,frontend,"react redux, angular, vue.js, html, css, javas...","lead frontend development for saas products, i..."
443,frontend,"react redux, angular, vue.js, html, css, javas...",build and optimize frontend for media streamin...
444,frontend,"react redux, angular, vue.js, html, css, javas...","lead frontend for ai-powered dashboards, build..."

In [15]:
df_final['description'] = df_final['description'].astype(str).str.strip()
df_final

,role,skills,description
100,backend,"node.js, python, java, express.js, flask, djan...","assist in building server-side applications, d..."
101,backend,"node.js, python, java, express.js, flask, djan...","implement scalable backend services, develop a..."
102,backend,"node.js, python, express.js, flask, django, my...","develop and maintain backend apis, optimize da..."
103,backend,"node.js, python, express.js, flask, django, my...",server-side development for web and mobile app...
104,backend,"node.js, python, java, express.js, flask, djan...","design and develop backend services, write eff..."
105,backend,"node.js, python, java, express.js, flask, djan...","develop backend modules, assist in api develop..."
106,backend,"node.js, python, express.js, django, flask, my...",assist in developing backend services for web ...
107,backend,"node.js, python, java, express.js, django, fla...",server-side components for web and mobile apps...
108,backend,"node.js, python, express.js, flask, django, my...",assist in backend development of scalable apis...
109,backend,"node.js, python, java, express.js, django, fla...","assist in backend development, develop apis, m..."
110,backend,"node.js, python, java, go, express.js, django,...","design, develop, and maintain backend services..."
111,backend,"java, go, node.js, spring boot, express.js, po...",lead backend development for fintech applicati...
112,backend,"python, node.js, django, flask, express.js, po...",architect backend systems for healthcare appli...
113,backend,"node.js, python, java, express.js, django, fla...",lead backend engineering for e-commerce platfo...
114,backend,"python, node.js, go, django, flask, express.js...",design backend services for ai-powered applica...
115,backend,"node.js, java, python, express.js, spring boot...",lead backend infrastructure for logistics plat...
116,backend,"python, node.js, java, django, flask, express....",architect backend solutions for saas applicati...
117,backend,"java, go, python, spring boot, express.js, dja...",develop backend systems for fintech and bankin...
118,backend,"node.js, python, java, express.js, django, spr...",lead backend development for large-scale socia...
119,backend,"node.js, python, go, express.js, django, flask...",architect backend solutions for media streamin...
300,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist in analyzing datasets, create dashboard..."
301,data analyst,"sql, python, r, tableau, power bi, excel chart...","perform data extraction and cleaning, create v..."
302,data analyst,"sql, python, r, sas, tableau, power bi, matplo...",assist with data cleaning and exploratory data...
303,data analyst,"sql, python, r, tableau, power bi, excel, pand...","support data extraction and cleaning, generate..."
304,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist in cleaning datasets, build simple dash..."
305,data analyst,"sql, python, r, tableau, power bi, matplotlib,...","support teams in analyzing datasets, perform d..."
306,data analyst,"sql, python, r, tableau, power bi, excel chart...","assist in etl processes, perform data cleaning..."
307,data analyst,"sql, python, r, tableau, power bi, excel chart...","perform data cleaning, generate dashboards, as..."
308,data analyst,"sql, python, r, sas, tableau, power bi, matplo...","assist teams with sql queries, process data us..."
309,data analyst,"predictive modeling, machine learning algorith...","lead analytics projects, develop predictive mo..."
310,data analyst,"predictive modeling, machine learning, time-se...",design and implement advanced analytics soluti...
311,data analyst,"predictive modeling, advanced analytics, machi...","lead business intelligence projects, develop p..."
312,data analyst,"advanced sql, python, r, predictive modeling, ...","develop advanced dashboards, optimize sql quer..."
313,data analyst,"predictive modeling, machine learning, advance...","lead analytics and bi projects, manage data pi..."
314,data analyst,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt..."
315,data analyst,"advanced sql, python, r, predictive modeling, ...","lead analytics initiatives, design predictive ..."
316,data analyst,"advanced sql, python, r, sas, predictive model...","manage large-scale analytics projects, impleme..."
317,data analyst,"advanced sql, python, r, predictive modeling, ...","design and implement analytics dashboards, opt..."
318,data analyst,"advanced sql, python, r, predictive modeling, ...","lead analytics and bi projects, manage data pi..."
319,data analyst,"advanced sql, python, r, predictive modeling, ...","manage large-scale analytics projects, impleme..."
342,data analyst,"python, r, sql, pandas, numpy, matplotlib, sea...","assist in data collection, cleaning, and analy..."
427,frontend,"html, css, javascript, react basics, angular b...","build responsive and interactive web pages, im..."
428,frontend,"html5, css3, javascript es6+ , react, vue.js,...","develop web interfaces for internal tools, imp..."
429,frontend,"html, css, javascript, react basics, angular b...",work on small projects and personal applicatio...
430,frontend,"html5, css3, javascript es6+ , react basics, ...",assist in designing and coding responsive web ...
431,frontend,"html, css, javascript, react basics, angular b...","create and maintain frontend components, parti..."
432,frontend,"html, css, javascript, react basics, angular b...",develop interactive ui pages for internal dash...
433,frontend,"html, css, javascript, react basics, vue.js ba...",assist in implementing ui features for web app...
434,frontend,"html, css, javascript, react basics, angular b...","build responsive web pages, assist in integrat..."
435,frontend,"html, css, javascript, react basics, vue.js ba...",assist in creating web interfaces and componen...
436,frontend,"html, css, javascript, react basics, angular b...","work on academic and personal projects, develo..."
437,frontend,"html5, css3, javascript es6+ , react redux, a...",design and develop advanced frontend applicati...
438,frontend,"react redux, angular, vue.js, html, css, javas...",lead frontend development for scalable applica...
439,frontend,"advanced react, angular, vue.js, html, css, ja...","architect and implement frontend solutions, le..."
440,frontend,"react redux, angular, vue.js, html, css, javas...",lead frontend initiatives for e-commerce platf...
441,frontend,"advanced react hooks, redux , angular, vue.js...","architect scalable web dashboards and spas, op..."
442,frontend,"react redux, angular, vue.js, html, css, javas...","lead frontend development for saas products, i..."
443,frontend,"react redux, angular, vue.js, html, css, javas...",build and optimize frontend for media streamin...
444,frontend,"react redux, angular, vue.js, html, css, javas...","lead frontend for ai-powered dashboards, build..."

In [17]:
df_final.to_csv('data6.csv', index=False)