# Preprocessing Data Analyst Job Roles in Canada Folder

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
id = '1ueakxNkchyy-E9QOQ9j3IVl8vAgguHUJ'
url = f'https://drive.google.com/uc?id={id}'
df = pd.read_csv(url)
df.head()

,Job Title,Job Info,Position,Employer,City,Province,Skill,Seniority,Work Type,Industry Type,Min_Salary,Max_Salary,Avg_Salary
0,Systems and Data Analysts,Binance Accelerator Program - Data Analyst (Risk),Risk Analyst,Binance,Remote,Undef,"Python, Sql",ANY,Remote,Others,76000.00,89440.0,82720.000
1,Business and Marketing Analysts,Business Analyst,Business Analyst,Canadian Nuclear Laboratories,Remote,Undef,"Power Bi, Power BI, Excel",ANY,Remote,Others,65000.00,87000.0,76000.000
2,Business and Technical Analysts,Geophysicist/Data Analyst,Data Analyst,Sander Geophysics Limited,Ottawa,ON,Undef,ANY,In-Person,Technology,64123.59,86600.0,75361.795
3,Systems and Data Analysts,Business Intelligence Data Engineer,Data Engineer,"Maximus Services, LLC",Toronto,ON,"Fabric, Power BI, Sql, Machine Learning, Genes...",ANY,In-Person,Service,87875.00,105000.0,96437.500
4,Systems and Data Analysts,"BUSINESS INTELLIGENCE SPECIALIST, FT",Data Specialist,Niagara Health System,Niagara,ON,"Azure, Power BI, SQL, Aws",Senior,In-Person,Healthcare,115211.20,130332.8,122772.000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1796 entries, 0 to 1795
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Job Title      1796 non-null   object
 1   Job Info       1796 non-null   object
 2   Position       1796 non-null   object
 3   Employer       1796 non-null   object
 4   City           1796 non-null   object
 5   Province       1796 non-null   object
 6   Skill          1796 non-null   object
 7   Seniority      1796 non-null   object
 8   Work Type      1796 non-null   object
 9   Industry Type  1796 non-null   object
 10  Min_Salary     1796 non-null   float64
 11  Max_Salary     1796 non-null   float64
 12  Avg_Salary     1796 non-null   float64
dtypes: float64(3), object(10)
memory usage: 182.5+ KB

In [4]:
df.columns

Index(['Job Title', 'Job Info', 'Position', 'Employer', 'City', 'Province',
       'Skill', 'Seniority', 'Work Type', 'Industry Type', 'Min_Salary',
       'Max_Salary', 'Avg_Salary'],
      dtype='object')

In [5]:
df = df[['Position', 'Skill']].copy()
df.head()

           Position                                              Skill
0      Risk Analyst                                        Python, Sql
1  Business Analyst                          Power Bi, Power BI, Excel
2      Data Analyst                                              Undef
3     Data Engineer  Fabric, Power BI, Sql, Machine Learning, Genes...
4   Data Specialist                          Azure, Power BI, SQL, Aws

In [6]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1156 entries, 0 to 1795
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Position  1156 non-null   object
 1   Skill     1156 non-null   object
dtypes: object(2)
memory usage: 27.1+ KB

In [7]:
# Role Normalization

def map_role(title):
    title = title.lower()
    
    if 'data analyst' in title:
        return 'data analyst'
    elif 'frontend' in title or 'front end' in title or 'react' in title or 'front-end' in title:
        return 'frontend'
    elif "backend" in title or 'back end' in title or "node" in title or 'back-end' in title:
        return "backend"
    else:
        return None
df['role'] = df['Position'].apply(map_role)
df = df[df['role'].notnull()].copy()
df

,Position,Skill,role
2,Data Analyst,Undef,data analyst
21,Data Analyst,"Sql, Tableau, Python, Database, Excel, Power B...",data analyst
46,Data Analyst,"Power BI, Confluence",data analyst
47,Data Analyst,"Sql, Aws, Databricks, Gap, Azure, Power Bi, Py...",data analyst
49,Data Analyst,"Database, Excel, Power Bi, Python, R, Database",data analyst
...,...,...,...
1662,Data Analyst,"Tableau, Computer science, Power BI, Data mode...",data analyst
1672,Data Analyst,"Bilingual, Tableau, Power BI, SQL, Laboratory ...",data analyst
1701,Data Analyst,"Power BI, SQL, SQL, Python",data analyst
1724,Data Analyst,"SQL, Big data, R, SQL, Data management",data analyst
1760,Data Analyst,"Power BI, SQL, Financial auditing, SAS, Tableau",data analyst

In [8]:
import re

def casefolding(text):
    return text.lower()

def cleaning(text):
    text = re.sub(r"http\S+", "", text)
    
    text = text.replace('\n', ' ')
    text = text.replace('*','')
    
    text = text.strip()
    
    text = re.sub(r'\s+', ' ', text)
    
    return text

for col in df.columns:
    df.loc[:, f"clean_{col}"] = df[col].apply(casefolding)
    df.loc[:, f"clean_{col}"] = df[f"clean_{col}"].apply(cleaning)
df

,Position,Skill,role,clean_Position,clean_Skill,clean_role
2,Data Analyst,Undef,data analyst,data analyst,undef,data analyst
21,Data Analyst,"Sql, Tableau, Python, Database, Excel, Power B...",data analyst,data analyst,"sql, tableau, python, database, excel, power b...",data analyst
46,Data Analyst,"Power BI, Confluence",data analyst,data analyst,"power bi, confluence",data analyst
47,Data Analyst,"Sql, Aws, Databricks, Gap, Azure, Power Bi, Py...",data analyst,data analyst,"sql, aws, databricks, gap, azure, power bi, py...",data analyst
49,Data Analyst,"Database, Excel, Power Bi, Python, R, Database",data analyst,data analyst,"database, excel, power bi, python, r, database",data analyst
...,...,...,...,...,...,...
1662,Data Analyst,"Tableau, Computer science, Power BI, Data mode...",data analyst,data analyst,"tableau, computer science, power bi, data mode...",data analyst
1672,Data Analyst,"Bilingual, Tableau, Power BI, SQL, Laboratory ...",data analyst,data analyst,"bilingual, tableau, power bi, sql, laboratory ...",data analyst
1701,Data Analyst,"Power BI, SQL, SQL, Python",data analyst,data analyst,"power bi, sql, sql, python",data analyst
1724,Data Analyst,"SQL, Big data, R, SQL, Data management",data analyst,data analyst,"sql, big data, r, sql, data management",data analyst
1760,Data Analyst,"Power BI, SQL, Financial auditing, SAS, Tableau",data analyst,data analyst,"power bi, sql, financial auditing, sas, tableau",data analyst

In [9]:
df['role'].value_counts()

role
data analyst    175
Name: count, dtype: int64

In [10]:
df_final = df[['role', 'clean_Skill']].copy()
df_final

              role                                        clean_Skill
2     data analyst                                              undef
21    data analyst  sql, tableau, python, database, excel, power b...
46    data analyst                               power bi, confluence
47    data analyst  sql, aws, databricks, gap, azure, power bi, py...
49    data analyst     database, excel, power bi, python, r, database
...            ...                                                ...
1662  data analyst  tableau, computer science, power bi, data mode...
1672  data analyst  bilingual, tableau, power bi, sql, laboratory ...
1701  data analyst                         power bi, sql, sql, python
1724  data analyst             sql, big data, r, sql, data management
1760  data analyst    power bi, sql, financial auditing, sas, tableau

[175 rows x 2 columns]

In [11]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, 2 to 1760
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   role         175 non-null    object
 1   clean_Skill  175 non-null    object
dtypes: object(2)
memory usage: 4.1+ KB

In [12]:
df_final.rename(columns={'clean_Skill': 'skills'}, inplace=True)
df_final

              role                                             skills
2     data analyst                                              undef
21    data analyst  sql, tableau, python, database, excel, power b...
46    data analyst                               power bi, confluence
47    data analyst  sql, aws, databricks, gap, azure, power bi, py...
49    data analyst     database, excel, power bi, python, r, database
...            ...                                                ...
1662  data analyst  tableau, computer science, power bi, data mode...
1672  data analyst  bilingual, tableau, power bi, sql, laboratory ...
1701  data analyst                         power bi, sql, sql, python
1724  data analyst             sql, big data, r, sql, data management
1760  data analyst    power bi, sql, financial auditing, sas, tableau

[175 rows x 2 columns]