# Preprocessing Skill-Based Task Assignment Folder

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
id = '1TSpofntP0RG0w8L7QhOkh4sEA0_sr861'
url = f'https://drive.google.com/uc?id={id}'
df = pd.read_csv(url)
df.head()

                Task Description Category        Skill
0  Implement user authentication  backend  spring boot
1    Optimize server performance  backend      asp.net
2     Manage database operations  backend       django
3  Implement user authentication  backend          api
4           Build a microservice  backend       kotlin

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20122 entries, 0 to 20121
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Task Description  20122 non-null  object
 1   Category          20122 non-null  object
 2   Skill             20122 non-null  object
dtypes: object(3)
memory usage: 471.7+ KB

In [4]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 789 entries, 0 to 20121
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Task Description  789 non-null    object
 1   Category          789 non-null    object
 2   Skill             789 non-null    object
dtypes: object(3)
memory usage: 24.7+ KB

In [5]:
# Role Normalization

def map_role(title):
    title = title.lower()
    
    if 'data analyst' in title:
        return 'data analyst'
    elif 'frontend' in title or 'front end' in title or 'react' in title or 'front-end' in title:
        return 'frontend'
    elif "backend" in title or 'back end' in title or "node" in title or 'back-end' in title:
        return "backend"
    else:
        return None
df['role'] = df['Category'].apply(map_role)
df = df[df['role'].notnull()].copy()
df

                        Task Description  Category        Skill      role
0          Implement user authentication   backend  spring boot   backend
1            Optimize server performance   backend      asp.net   backend
2             Manage database operations   backend       django   backend
3          Implement user authentication   backend          api   backend
4                   Build a microservice   backend       kotlin   backend
...                                  ...       ...          ...       ...
13168  Implement accessibility standards  frontend         aria  frontend
13169       Add animations to improve UX  frontend         gsap  frontend
13170      Create reusable UI components  frontend        react  frontend
13171          Implement dark mode theme  frontend          css  frontend
13172     Optimize website loading speed  frontend      webpack  frontend

[234 rows x 4 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234 entries, 0 to 13172
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Task Description  234 non-null    object
 1   Category          234 non-null    object
 2   Skill             234 non-null    object
 3   role              234 non-null    object
dtypes: object(4)
memory usage: 9.1+ KB

In [7]:
import re

def casefolding(text):
    return text.lower()

def cleaning(text):
    text = re.sub(r"http\S+", "", text)
    
    text = text.replace('\n', ' ')
    text = text.replace('*','')
    
    text = text.strip()
    
    text = re.sub(r'\s+', ' ', text)
    
    return text

for col in df.columns:
    df.loc[:, f"clean_{col}"] = df[col].apply(casefolding)
    df.loc[:, f"clean_{col}"] = df[f"clean_{col}"].apply(cleaning)
df

,Task Description,Category,Skill,role,clean_Task Description,clean_Category,clean_Skill,clean_role
0,Implement user authentication,backend,spring boot,backend,implement user authentication,backend,spring boot,backend
1,Optimize server performance,backend,asp.net,backend,optimize server performance,backend,asp.net,backend
2,Manage database operations,backend,django,backend,manage database operations,backend,django,backend
3,Implement user authentication,backend,api,backend,implement user authentication,backend,api,backend
4,Build a microservice,backend,kotlin,backend,build a microservice,backend,kotlin,backend
...,...,...,...,...,...,...,...,...
13168,Implement accessibility standards,frontend,aria,frontend,implement accessibility standards,frontend,aria,frontend
13169,Add animations to improve UX,frontend,gsap,frontend,add animations to improve ux,frontend,gsap,frontend
13170,Create reusable UI components,frontend,react,frontend,create reusable ui components,frontend,react,frontend
13171,Implement dark mode theme,frontend,css,frontend,implement dark mode theme,frontend,css,frontend
13172,Optimize website loading speed,frontend,webpack,frontend,optimize website loading speed,frontend,webpack,frontend

In [8]:
df['role'].value_counts()

role
backend     122
frontend    112
Name: count, dtype: int64

In [9]:
df_final = df[['role', 'clean_Skill', 'clean_Task Description']].copy()
df_final

           role  clean_Skill             clean_Task Description
0       backend  spring boot      implement user authentication
1       backend      asp.net        optimize server performance
2       backend       django         manage database operations
3       backend          api      implement user authentication
4       backend       kotlin               build a microservice
...         ...          ...                                ...
13168  frontend         aria  implement accessibility standards
13169  frontend         gsap       add animations to improve ux
13170  frontend        react      create reusable ui components
13171  frontend          css          implement dark mode theme
13172  frontend      webpack     optimize website loading speed

[234 rows x 3 columns]

In [13]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234 entries, 0 to 13172
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   role                    234 non-null    object
 1   clean_Skill             234 non-null    object
 2   clean_Task Description  234 non-null    object
dtypes: object(3)
memory usage: 7.3+ KB

In [15]:
df_final.rename(columns={'clean_Skill': 'skills', 'clean_Task Description': 'description'}, inplace=True)
df_final

           role       skills                        description
0       backend  spring boot      implement user authentication
1       backend      asp.net        optimize server performance
2       backend       django         manage database operations
3       backend          api      implement user authentication
4       backend       kotlin               build a microservice
...         ...          ...                                ...
13168  frontend         aria  implement accessibility standards
13169  frontend         gsap       add animations to improve ux
13170  frontend        react      create reusable ui components
13171  frontend          css          implement dark mode theme
13172  frontend      webpack     optimize website loading speed

[234 rows x 3 columns]