# Preprocessing stackoverflow survey Folder

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
id = '1ElgvODvXhWuWPe4hnr90J3u0SLBlgl0I'
url = f'https://drive.google.com/uc?id={id}'
df = pd.read_csv(url)
df.head()

,ResponseId,MainBranch,CodingActivities,EdLevel,LearnCode,YearsCode,DevType,Country,LanguageHaveWorkedWith,LanguageWantToWorkWith,...,PlatformHaveWorkedWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,AISearchHaveWorkedWith
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,18,"Senior Executive (C-Suite, VP, etc.)",United States of America,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,...,Amazon Web Services (AWS);Netlify;Vercel,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,MacOS;Windows;Windows Subsystem for Linux (WSL),ChatGPT
2,3,I am a developer by profession,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,27,"Developer, back-end",United States of America,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,...,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,NaN
3,4,I am a developer by profession,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,12,"Developer, front-end",United States of America,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,...,Cloudflare;Heroku,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,NaN
4,5,I am a developer by profession,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,6,"Developer, full-stack",Philippines,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,...,Amazon Web Services (AWS);Firebase;Heroku;Netl...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,ChatGPT

In [3]:
skill_cols = [
    'LanguageHaveWorkedWith',
    'WebframeHaveWorkedWith',
    'MiscTechHaveWorkedWith',
    'ToolsTechHaveWorkedWith'
]

df = df.copy()

df['skills'] = df[skill_cols].fillna('').agg('; '.join, axis=1)
df.head()

,ResponseId,MainBranch,CodingActivities,EdLevel,LearnCode,YearsCode,DevType,Country,LanguageHaveWorkedWith,LanguageWantToWorkWith,...,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,AISearchHaveWorkedWith,skills
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,; ; ;
1,2,I am a developer by profession,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,18,"Senior Executive (C-Suite, VP, etc.)",United States of America,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,...,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,MacOS;Windows;Windows Subsystem for Linux (WSL),ChatGPT,HTML/CSS;JavaScript;Python; Next.js;React;Remi...
2,3,I am a developer by profession,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,27,"Developer, back-end",United States of America,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,...,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,NaN,Bash/Shell (all shells);Go; ; ; Cargo;Docker;K...
3,4,I am a developer by profession,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,12,"Developer, front-end",United States of America,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,...,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,NaN,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...
4,5,I am a developer by profession,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,6,"Developer, full-stack",Philippines,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,ChatGPT,HTML/CSS;JavaScript;TypeScript; Express;Gatsby...

In [63]:
df = df[['DevType', 'skills']].copy()
df.head()

                 DevType                                             skills
2    Developer, back-end  Bash/Shell (all shells);Go; ; ; Cargo;Docker;K...
3   Developer, front-end  Bash/Shell (all shells);HTML/CSS;JavaScript;PH...
5    Developer, back-end  Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...
15   Developer, back-end  Bash/Shell (all shells);Dart;Go;Haskell;HTML/C...
16  Developer, front-end  JavaScript;TypeScript; Express;Gatsby;Next.js;...

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18078 entries, 2 to 89180
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DevType  18078 non-null  object
 1   skills   18078 non-null  object
dtypes: object(2)
memory usage: 423.7+ KB

In [65]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18078 entries, 2 to 89180
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DevType  18078 non-null  object
 1   skills   18078 non-null  object
dtypes: object(2)
memory usage: 423.7+ KB

In [66]:
# Role Normalization

def map_role(title):
    title = title.lower()
    
    if 'data analyst' in title:
        return 'data analyst'
    elif 'frontend' in title or 'front end' in title or 'react' in title or 'front-end' in title:
        return 'frontend'
    elif "backend" in title or 'back end' in title or "node" in title or 'back-end' in title:
        return "backend"
    else:
        return None
df['role'] = df['DevType'].apply(map_role)
df = df[df['role'].notnull()].copy()
df

,DevType,skills,role
2,"Developer, back-end",Bash/Shell (all shells);Go; ; ; Cargo;Docker;K...,backend
3,"Developer, front-end",Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,frontend
5,"Developer, back-end",Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,backend
15,"Developer, back-end",Bash/Shell (all shells);Dart;Go;Haskell;HTML/C...,backend
16,"Developer, front-end",JavaScript;TypeScript; Express;Gatsby;Next.js;...,frontend
...,...,...,...
89162,"Developer, back-end",C;C++; ; ; CMake;GNU GCC;Make;MSBuild;MSVC;QMa...,backend
89164,"Developer, back-end",Go;HTML/CSS;Java;JavaScript;Python; Django;Exp...,backend
89165,"Developer, back-end",C;C#;C++;Java;JavaScript;TypeScript; Angular;D...,backend
89179,"Developer, front-end",HTML/CSS;Java;JavaScript;SQL;TypeScript; Angul...,frontend
89180,"Developer, back-end",Dart;Java;Python;SQL; Spring Boot; Flutter;Ope...,backend

In [69]:
import re

def casefolding(text):
    return text.lower()

def cleaning(text):
    text = re.sub(r"http\S+", "", text)
    
    text = text.replace('\n', ' ')
    text = text.replace('*','')
    text = text.replace(';',', ')
    text = re.sub(r',\s*,+', ',', text)
    text = text.strip()
    
    text = re.sub(r'\s+', ' ', text)
    
    return text

for col in df.columns:
    df.loc[:, f"clean_{col}"] = df[col].apply(casefolding)
    df.loc[:, f"clean_{col}"] = df[f"clean_{col}"].apply(cleaning)
df

,DevType,skills,role,clean_DevType,clean_skills,clean_role,clean_clean_DevType,clean_clean_skills,clean_clean_role,clean_clean_clean_DevType,clean_clean_clean_skills,clean_clean_clean_role
2,"Developer, back-end",Bash/Shell (all shells);Go; ; ; Cargo;Docker;K...,backend,"developer, back-end","bash/shell (all shells), go, , cargo, docker, ...",backend,"developer, back-end","bash/shell (all shells), go, cargo, docker, ku...",backend,"developer, back-end","bash/shell (all shells), go, cargo, docker, ku...",backend
3,"Developer, front-end",Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,frontend,"developer, front-end","bash/shell (all shells), html/css, javascript,...",frontend,"developer, front-end","bash/shell (all shells), html/css, javascript,...",frontend,"developer, front-end","bash/shell (all shells), html/css, javascript,...",frontend
5,"Developer, back-end",Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,backend,"developer, back-end","bash/shell (all shells), html/css, javascript,...",backend,"developer, back-end","bash/shell (all shells), html/css, javascript,...",backend,"developer, back-end","bash/shell (all shells), html/css, javascript,...",backend
15,"Developer, back-end",Bash/Shell (all shells);Dart;Go;Haskell;HTML/C...,backend,"developer, back-end","bash/shell (all shells), dart, go, haskell, ht...",backend,"developer, back-end","bash/shell (all shells), dart, go, haskell, ht...",backend,"developer, back-end","bash/shell (all shells), dart, go, haskell, ht...",backend
16,"Developer, front-end",JavaScript;TypeScript; Express;Gatsby;Next.js;...,frontend,"developer, front-end","javascript, typescript, express, gatsby, next....",frontend,"developer, front-end","javascript, typescript, express, gatsby, next....",frontend,"developer, front-end","javascript, typescript, express, gatsby, next....",frontend
...,...,...,...,...,...,...,...,...,...,...,...,...
89162,"Developer, back-end",C;C++; ; ; CMake;GNU GCC;Make;MSBuild;MSVC;QMa...,backend,"developer, back-end","c, c++, , cmake, gnu gcc, make, msbuild, msvc,...",backend,"developer, back-end","c, c++, cmake, gnu gcc, make, msbuild, msvc, q...",backend,"developer, back-end","c, c++, cmake, gnu gcc, make, msbuild, msvc, q...",backend
89164,"Developer, back-end",Go;HTML/CSS;Java;JavaScript;Python; Django;Exp...,backend,"developer, back-end","go, html/css, java, javascript, python, django...",backend,"developer, back-end","go, html/css, java, javascript, python, django...",backend,"developer, back-end","go, html/css, java, javascript, python, django...",backend
89165,"Developer, back-end",C;C#;C++;Java;JavaScript;TypeScript; Angular;D...,backend,"developer, back-end","c, c#, c++, java, javascript, typescript, angu...",backend,"developer, back-end","c, c#, c++, java, javascript, typescript, angu...",backend,"developer, back-end","c, c#, c++, java, javascript, typescript, angu...",backend
89179,"Developer, front-end",HTML/CSS;Java;JavaScript;SQL;TypeScript; Angul...,frontend,"developer, front-end","html/css, java, javascript, sql, typescript, a...",frontend,"developer, front-end","html/css, java, javascript, sql, typescript, a...",frontend,"developer, front-end","html/css, java, javascript, sql, typescript, a...",frontend
89180,"Developer, back-end",Dart;Java;Python;SQL; Spring Boot; Flutter;Ope...,backend,"developer, back-end","dart, java, python, sql, spring boot, flutter,...",backend,"developer, back-end","dart, java, python, sql, spring boot, flutter,...",backend,"developer, back-end","dart, java, python, sql, spring boot, flutter,...",backend

In [70]:
df['role'].value_counts()

role
backend     13276
frontend     4802
Name: count, dtype: int64

In [73]:
df_final = df[['role', 'clean_clean_clean_skills']].copy()
df_final

           role                           clean_clean_clean_skills
2       backend  bash/shell (all shells), go, cargo, docker, ku...
3      frontend  bash/shell (all shells), html/css, javascript,...
5       backend  bash/shell (all shells), html/css, javascript,...
15      backend  bash/shell (all shells), dart, go, haskell, ht...
16     frontend  javascript, typescript, express, gatsby, next....
...         ...                                                ...
89162   backend  c, c++, cmake, gnu gcc, make, msbuild, msvc, q...
89164   backend  go, html/css, java, javascript, python, django...
89165   backend  c, c#, c++, java, javascript, typescript, angu...
89179  frontend  html/css, java, javascript, sql, typescript, a...
89180   backend  dart, java, python, sql, spring boot, flutter,...

[18078 rows x 2 columns]

In [74]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18078 entries, 2 to 89180
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   role                      18078 non-null  object
 1   clean_clean_clean_skills  18078 non-null  object
dtypes: object(2)
memory usage: 423.7+ KB

In [75]:
df_final.rename(columns={'clean_clean_clean_skills': 'skills'}, inplace=True)
df_final

           role                                             skills
2       backend  bash/shell (all shells), go, cargo, docker, ku...
3      frontend  bash/shell (all shells), html/css, javascript,...
5       backend  bash/shell (all shells), html/css, javascript,...
15      backend  bash/shell (all shells), dart, go, haskell, ht...
16     frontend  javascript, typescript, express, gatsby, next....
...         ...                                                ...
89162   backend  c, c++, cmake, gnu gcc, make, msbuild, msvc, q...
89164   backend  go, html/css, java, javascript, python, django...
89165   backend  c, c#, c++, java, javascript, typescript, angu...
89179  frontend  html/css, java, javascript, sql, typescript, a...
89180   backend  dart, java, python, sql, spring boot, flutter,...

[18078 rows x 2 columns]