# Preprocessing Internshala Jobs Dataset Folder

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
id = '1aOvtU7cv-7lVE4GPIe6fEmF2SjJaCDoO'
url = f'https://drive.google.com/uc?id={id}'
df = pd.read_csv(url)
df.head()

,Company_Name,JobTitles,Skills,Description,Stipend,Links
0,Bauer Bodoni,WordPress Development Intern,WordPress,Are you a WordPress whiz looking to gain hands...,"₹ 15,000-20,000 /month",https://internshala.com/internship/detail/word...
1,Bauer Bodoni,WordPress Development Intern,"MS-PowerPoint , WordPress",As a WordPress Development intern at Bauer Bod...,"₹ 15,000-20,000 /month",https://internshala.com/internship/detail/word...
2,ESSI Integrated Technologies,ERPNext And HRMS Admin Intern,"Accounting , Enterprise Resource Planning(ERP)...",Selected intern's day-to-day responsibilities ...,"₹ 10,000 /month",https://internshala.com/internship/detail/erpn...
3,Growify Digital,Website Operation Intern,"JavaScript , WordPress",Selected intern's day-to-day responsibilities ...,"₹ 10,000-15,000 /month",https://internshala.com/internship/detail/webs...
4,Confluencr,Influencer Marketing Data Analytics Intern,"Digital Advertising , English Proficiency (Spo...",Selected intern's day-to-day responsibilities ...,"₹ 20,000 /month",https://internshala.com/internship/detail/infl...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431 entries, 0 to 430
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company_Name  431 non-null    object
 1   JobTitles     431 non-null    object
 2   Skills        431 non-null    object
 3   Description   431 non-null    object
 4   Stipend       431 non-null    object
 5   Links         431 non-null    object
dtypes: object(6)
memory usage: 20.3+ KB

In [4]:
df.columns

Index(['Company_Name', 'JobTitles', 'Skills', 'Description', 'Stipend',
       'Links'],
      dtype='object')

In [5]:
df.drop(columns=['Company_Name', 'Stipend', 'Links'], inplace=True)
df.head()

,JobTitles,Skills,Description
0,WordPress Development Intern,WordPress,Are you a WordPress whiz looking to gain hands...
1,WordPress Development Intern,"MS-PowerPoint , WordPress",As a WordPress Development intern at Bauer Bod...
2,ERPNext And HRMS Admin Intern,"Accounting , Enterprise Resource Planning(ERP)...",Selected intern's day-to-day responsibilities ...
3,Website Operation Intern,"JavaScript , WordPress",Selected intern's day-to-day responsibilities ...
4,Influencer Marketing Data Analytics Intern,"Digital Advertising , English Proficiency (Spo...",Selected intern's day-to-day responsibilities ...

In [6]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431 entries, 0 to 430
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   JobTitles    431 non-null    object
 1   Skills       431 non-null    object
 2   Description  431 non-null    object
dtypes: object(3)
memory usage: 10.2+ KB

In [7]:
# Role Normalization

def map_role(title):
    title = title.lower()
    
    if 'data analyst' in title:
        return 'data analyst'
    elif 'frontend' in title or 'front end' in title or 'react' in title or 'front-end' in title:
        return 'frontend'
    elif "backend" in title or 'back end' in title or "node" in title or 'back-end' in title:
        return "backend"
    else:
        return None
df['role'] = df['JobTitles'].apply(map_role)
df = df[df['role'].notnull()].copy()
df

,JobTitles,Skills,Description,role
22,Backend Development Intern,"Amazon Web Server (AWS) , Hadoop , MySQL , Python",Mush should be eager to learn and develop skil...,backend
24,Front End Development Intern,"CSS , HTML , HTML&CSS , JavaScript",As a front-end development intern at Consumabl...,frontend
36,Frontend Development + Technical Content Writi...,"JavaScript , Node.js , React , TypeScript","At Middleware, you'll be working very closely ...",frontend
37,Reactjs Development Intern (Part time/Remote),"Figma , GitHub , HTML , JavaScript , ReactJS",The selected intern's day-to-day responsibilit...,frontend
38,React Native App Developer Intern (Remote),React Native,Selected intern's day-to-day responsibilities ...,frontend
...,...,...,...,...
421,Reactjs Development Intern,"Figma , HTML&CSS , Tailwind CSS , TypeScript",We are seeking a talented and motivated indivi...,frontend
422,Node.js Development Intern,"Angular 7.0 , CSS , GitHub , JavaScript , Node...",Selected intern's day-to-day responsibilities ...,backend
425,Front End Development Intern (Remote),"CSS , HTML , MongoDB , Node.js , React",Selected intern's day-to-day responsibilities ...,frontend
426,Front End Development Intern,"HTML&CSS , JavaScript , UI & UX Design , WordP...",Selected intern's day-to-day responsibilities ...,frontend
427,React Native Development Intern (Remote),"Data Analysis , Data Science , Python , R Prog...",Selected intern's day-to-day responsibilities ...,frontend

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 22 to 427
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   JobTitles    61 non-null     object
 1   Skills       61 non-null     object
 2   Description  61 non-null     object
 3   role         61 non-null     object
dtypes: object(4)
memory usage: 2.4+ KB

In [9]:
import re

def casefolding(text):
    return text.lower()

def cleaning(text):
    text = re.sub(r"http\S+", "", text)
    
    text = text.replace('\n', ' ')
    text = text.replace('*','')
    
    text = text.strip()
    
    text = re.sub(r'\s+', ' ', text)
    
    return text

for col in df.columns:
    df.loc[:, f"clean_{col}"] = df[col].apply(casefolding)
    df.loc[:, f"clean_{col}"] = df[f"clean_{col}"].apply(cleaning)
df

,JobTitles,Skills,Description,role,clean_JobTitles,clean_Skills,clean_Description,clean_role
22,Backend Development Intern,"Amazon Web Server (AWS) , Hadoop , MySQL , Python",Mush should be eager to learn and develop skil...,backend,backend development intern,"amazon web server (aws) , hadoop , mysql , python",mush should be eager to learn and develop skil...,backend
24,Front End Development Intern,"CSS , HTML , HTML&CSS , JavaScript",As a front-end development intern at Consumabl...,frontend,front end development intern,"css , html , html&css , javascript",as a front-end development intern at consumabl...,frontend
36,Frontend Development + Technical Content Writi...,"JavaScript , Node.js , React , TypeScript","At Middleware, you'll be working very closely ...",frontend,frontend development + technical content writi...,"javascript , node.js , react , typescript","at middleware, you'll be working very closely ...",frontend
37,Reactjs Development Intern (Part time/Remote),"Figma , GitHub , HTML , JavaScript , ReactJS",The selected intern's day-to-day responsibilit...,frontend,reactjs development intern (part time/remote),"figma , github , html , javascript , reactjs",the selected intern's day-to-day responsibilit...,frontend
38,React Native App Developer Intern (Remote),React Native,Selected intern's day-to-day responsibilities ...,frontend,react native app developer intern (remote),react native,selected intern's day-to-day responsibilities ...,frontend
...,...,...,...,...,...,...,...,...
421,Reactjs Development Intern,"Figma , HTML&CSS , Tailwind CSS , TypeScript",We are seeking a talented and motivated indivi...,frontend,reactjs development intern,"figma , html&css , tailwind css , typescript",we are seeking a talented and motivated indivi...,frontend
422,Node.js Development Intern,"Angular 7.0 , CSS , GitHub , JavaScript , Node...",Selected intern's day-to-day responsibilities ...,backend,node.js development intern,"angular 7.0 , css , github , javascript , node...",selected intern's day-to-day responsibilities ...,backend
425,Front End Development Intern (Remote),"CSS , HTML , MongoDB , Node.js , React",Selected intern's day-to-day responsibilities ...,frontend,front end development intern (remote),"css , html , mongodb , node.js , react",selected intern's day-to-day responsibilities ...,frontend
426,Front End Development Intern,"HTML&CSS , JavaScript , UI & UX Design , WordP...",Selected intern's day-to-day responsibilities ...,frontend,front end development intern,"html&css , javascript , ui & ux design , wordp...",selected intern's day-to-day responsibilities ...,frontend
427,React Native Development Intern (Remote),"Data Analysis , Data Science , Python , R Prog...",Selected intern's day-to-day responsibilities ...,frontend,react native development intern (remote),"data analysis , data science , python , r prog...",selected intern's day-to-day responsibilities ...,frontend

In [10]:
df['role'].value_counts()

role
frontend        36
backend         24
data analyst     1
Name: count, dtype: int64

In [11]:
df_final = df[['role', 'clean_Skills', 'clean_Description']].copy()
df_final

,role,clean_Skills,clean_Description
22,backend,"amazon web server (aws) , hadoop , mysql , python",mush should be eager to learn and develop skil...
24,frontend,"css , html , html&css , javascript",as a front-end development intern at consumabl...
36,frontend,"javascript , node.js , react , typescript","at middleware, you'll be working very closely ..."
37,frontend,"figma , github , html , javascript , reactjs",the selected intern's day-to-day responsibilit...
38,frontend,react native,selected intern's day-to-day responsibilities ...
...,...,...,...
421,frontend,"figma , html&css , tailwind css , typescript",we are seeking a talented and motivated indivi...
422,backend,"angular 7.0 , css , github , javascript , node...",selected intern's day-to-day responsibilities ...
425,frontend,"css , html , mongodb , node.js , react",selected intern's day-to-day responsibilities ...
426,frontend,"html&css , javascript , ui & ux design , wordp...",selected intern's day-to-day responsibilities ...
427,frontend,"data analysis , data science , python , r prog...",selected intern's day-to-day responsibilities ...

In [12]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 22 to 427
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   role               61 non-null     object
 1   clean_Skills       61 non-null     object
 2   clean_Description  61 non-null     object
dtypes: object(3)
memory usage: 1.9+ KB

In [13]:
df_final.rename(columns={'clean_Skills': 'skills', 'clean_Description': 'description'}, inplace=True)
df_final

,role,skills,description
22,backend,"amazon web server (aws) , hadoop , mysql , python",mush should be eager to learn and develop skil...
24,frontend,"css , html , html&css , javascript",as a front-end development intern at consumabl...
36,frontend,"javascript , node.js , react , typescript","at middleware, you'll be working very closely ..."
37,frontend,"figma , github , html , javascript , reactjs",the selected intern's day-to-day responsibilit...
38,frontend,react native,selected intern's day-to-day responsibilities ...
...,...,...,...
421,frontend,"figma , html&css , tailwind css , typescript",we are seeking a talented and motivated indivi...
422,backend,"angular 7.0 , css , github , javascript , node...",selected intern's day-to-day responsibilities ...
425,frontend,"css , html , mongodb , node.js , react",selected intern's day-to-day responsibilities ...
426,frontend,"html&css , javascript , ui & ux design , wordp...",selected intern's day-to-day responsibilities ...
427,frontend,"data analysis , data science , python , r prog...",selected intern's day-to-day responsibilities ...

In [14]:
def preprocessing_lanjutan(text):
    text = text.replace('/', ' ')
    text = text.replace('&', ' ')
    text = re.sub(r"[()]", " ", text)
    
    return text
    
df_final['skills'] = df_final['skills'].apply(preprocessing_lanjutan).copy()
df_final

,role,skills,description
22,backend,"amazon web server aws , hadoop , mysql , python",mush should be eager to learn and develop skil...
24,frontend,"css , html , html css , javascript",as a front-end development intern at consumabl...
36,frontend,"javascript , node.js , react , typescript","at middleware, you'll be working very closely ..."
37,frontend,"figma , github , html , javascript , reactjs",the selected intern's day-to-day responsibilit...
38,frontend,react native,selected intern's day-to-day responsibilities ...
...,...,...,...
421,frontend,"figma , html css , tailwind css , typescript",we are seeking a talented and motivated indivi...
422,backend,"angular 7.0 , css , github , javascript , node...",selected intern's day-to-day responsibilities ...
425,frontend,"css , html , mongodb , node.js , react",selected intern's day-to-day responsibilities ...
426,frontend,"html css , javascript , ui ux design , wordp...",selected intern's day-to-day responsibilities ...
427,frontend,"data analysis , data science , python , r prog...",selected intern's day-to-day responsibilities ...

In [15]:
df_final['description'] = df_final['description'].astype(str).str.strip()
df_final

,role,skills,description
22,backend,"amazon web server aws , hadoop , mysql , python",mush should be eager to learn and develop skil...
24,frontend,"css , html , html css , javascript",as a front-end development intern at consumabl...
36,frontend,"javascript , node.js , react , typescript","at middleware, you'll be working very closely ..."
37,frontend,"figma , github , html , javascript , reactjs",the selected intern's day-to-day responsibilit...
38,frontend,react native,selected intern's day-to-day responsibilities ...
...,...,...,...
421,frontend,"figma , html css , tailwind css , typescript",we are seeking a talented and motivated indivi...
422,backend,"angular 7.0 , css , github , javascript , node...",selected intern's day-to-day responsibilities ...
425,frontend,"css , html , mongodb , node.js , react",selected intern's day-to-day responsibilities ...
426,frontend,"html css , javascript , ui ux design , wordp...",selected intern's day-to-day responsibilities ...
427,frontend,"data analysis , data science , python , r prog...",selected intern's day-to-day responsibilities ...

In [17]:
df_final.to_csv('data7.csv', index=False)